// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFAEpJxU5KoNqpQJRN23ru9NKMYKEDe44',
    appId: '1:454688030249:web:d6bcf3aecfd3cdc8ec2638',
    messagingSenderId: '454688030249',
    projectId: 'robinfinal-d7a43',
    authDomain: 'robinfinal-d7a43.firebaseapp.com',
    storageBucket: 'robinfinal-d7a43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Pn-11tmSPrePxd2sI6Ng7RspSJuiDXU',
    appId: '1:454688030249:android:d50460dbaaf11d56ec2638',
    messagingSenderId: '454688030249',
    projectId: 'robinfinal-d7a43',
    storageBucket: 'robinfinal-d7a43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiJuRYc_YIxs5uLLw-HWtxvu2lKd1AG8c',
    appId: '1:454688030249:ios:f5ede64b601c8cefec2638',
    messagingSenderId: '454688030249',
    projectId: 'robinfinal-d7a43',
    storageBucket: 'robinfinal-d7a43.appspot.com',
    iosBundleId: 'com.example.robinfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiJuRYc_YIxs5uLLw-HWtxvu2lKd1AG8c',
    appId: '1:454688030249:ios:ae935a4b327f3305ec2638',
    messagingSenderId: '454688030249',
    projectId: 'robinfinal-d7a43',
    storageBucket: 'robinfinal-d7a43.appspot.com',
    iosBundleId: 'com.example.robinfinal.RunnerTests',
  );
}
